### ISSUE TITLE
Update checklist

### ISSUE THREAD

**Issue by tom-seddon** [tom-seddon/ghouls-revenge#132]
Probably going to be `V1.10`.

- [x] Collate any level updates
- [x] Fix score file names
- [x] Update web site
- [x] Post on Stardot

**Comment by tom-seddon** [comment]
- [ ] fix this: https://www.stardot.org.uk/forums/viewtopic.php?p=440518#p440518

**Comment by tom-seddon** [comment]
Minor tweaks that might be nice:

- [ ] you will _definitely_ see `Record not found` when merging the Bitshifters best times
- [ ] the README in the zip file is the same as the README on the ssd, so arranged for *TYPE on the BBC with some useful stuff at the end. Should have the instructions link duplicated at the top as well, which makes more sense when reading in Notepad

**Comment by tom-seddon** [comment]
- [ ] check there's enough DFS catalogue entries to run PTIMES (+1 file - output), then save a separate high score file (+1 file - the new score file), then run TMERGE (+1 file - the score backup)

**Comment by tom-seddon** [comment]
There's no V1.10 for download from GitHub - https://bitshifters.github.io/posts/prods/bs-ghouls-revenge.html is where you get the proper builds from.
